include:
  - project: "metatype/templates"
    ref: main
    file: "metatype.yml"
  - project: "devops/templates"
    ref: main
    file: "kaniko.yml"

variables: &variables
  DENO_VERSION: "1.28.2"
  DENO_BINDGEN_URL: https://github.com/denoland/deno_bindgen/raw/main/cli.ts
  RUST_VERSION: "1.65.0"
  PNPM_VERSION: "7.9.3"

stages:
  - test
  - deploy

test:
  stage: test
  tags:
    - docker
  variables:
    <<: *variables
    TEST_POSTGRES_DB: "postgresql://postgres:password@postgres:5432/db?schema=test"
    TEST_POSTGRES_DB2: "postgresql://postgres:password@postgres:5432/db?schema=test2"

kaniko:
  stage: test
  tags:
    - docker
  only:
    - main
  variables:
    KANIKO_DOCKERFILE: typegate/Dockerfile
    KANIKO_EXTRA_ARGS: |
      --build-arg DENO_VERSION
      --build-arg DENO_BINDGEN_URL 
      --build-arg RUST_VERSION
      --use-new-run
      --single-snapshot

package:
  stage: deploy
  needs:
    - test
    - kaniko
  tags:
    - docker
  only:
    - main
  variables:
    <<: *variables

deploy:
  stage: deploy
  needs:
    - test
    - kaniko
  only:
    - main
  variables:
    REF_SLUG: $CI_COMMIT_REF_SLUG
    CREATED_AT: $CI_PIPELINE_CREATED_AT
    SHORT_SHA: $CI_COMMIT_SHORT_SHA
  trigger:
    project: metatype/cloud
    branch: main
    strategy: depend
