[package]
name = "meta"
version = "0.0.2-alpha.1"
edition = "2021"


[dependencies]
dprint-plugin-typescript = "0.73.0"
swc = "0.232.15"
swc_common = { version = "0.29.7", features = ["tty-emitter"] }
swc_ecma_ast = "0.94.10"
swc_ecmascript = { version = "0.205.15", features = ["visit", "transforms", "typescript-parser", "parser", "codegen"] }
swc_ecma_transforms = "0.198.8"
datamodel = { git = "https://github.com/prisma/prisma-engines" }
lazy_static = "1.4.0"
tokio = { version = "1.20.1", features = ["full"] }
log = "0.4.17"
clap = { version = "3.2.17", features = ["derive"] }
crossbeam-channel = "0.5.6"
notify = "5.0.0-pre.16"
tiny_http = "0.11.0"
ignore = "0.4.18"
globset = "0.4.9"
anyhow = "1.0.62"
indoc = "1.0.7"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
reqwest = { version = "0.11.11", features = ["blocking", "json"] }
colored = "2.0.0"
question = "0.2.2"
dialoguer = "0.10.2"
flate2 = "1.0.24"
tar = "0.4.38"
base64 = "0.13.0"
common = { path = "../libs/common" }
