[tool.poetry]
name = "typegraph"
version = "0.1.9-dev.0"
description = "Open source, low-code backend platform for developers — build modular APIs with zero-trust and serverless deployment, no matter where and how (legacy) systems are."
authors = ["Metatype Contributors <support@metatype.dev>"]
license = "MPL-2.0"
homepage = "https://metatype.dev"
repository = "https://github.com/metatypedev/metatype"
include = ["typegraph/**/*", "LICENSE.md"]
keywords = ["api", "composition", "typesystem", "graphql", "ecosystem"]
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python",
]

[tool.poetry.scripts]
py-tg = "typegraph.utils.loaders:cmd"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
wasmtime = "^9.0.0"

[tool.pyright]
venvPath = "."
venv = ".venv"
